ALTER TABLE groups ADD COLUMN IF NOT EXISTS night_rate_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS night_start VARCHAR(5) NOT NULL DEFAULT '01:30';
ALTER TABLE groups ADD COLUMN IF NOT EXISTS night_end VARCHAR(5) NOT NULL DEFAULT '06:30';
ALTER TABLE groups ADD COLUMN IF NOT EXISTS night_rate_multiplier NUMERIC(10,4) NOT NULL DEFAULT 1.5;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS cache_read_multiplier NUMERIC(10,4) NOT NULL DEFAULT 2.0;
