// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/fileobject"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// FileObject is the model entity for the FileObject schema.
type FileObject struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// OwnerUserID holds the value of the "owner_user_id" field.
	OwnerUserID int64 `json:"owner_user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID *int64 `json:"api_key_id,omitempty"`
	// Purpose holds the value of the "purpose" field.
	Purpose string `json:"purpose,omitempty"`
	// StorageProvider holds the value of the "storage_provider" field.
	StorageProvider string `json:"storage_provider,omitempty"`
	// Bucket holds the value of the "bucket" field.
	Bucket string `json:"bucket,omitempty"`
	// ObjectKey holds the value of the "object_key" field.
	ObjectKey string `json:"object_key,omitempty"`
	// OriginalFilename holds the value of the "original_filename" field.
	OriginalFilename *string `json:"original_filename,omitempty"`
	// MimeType holds the value of the "mime_type" field.
	MimeType string `json:"mime_type,omitempty"`
	// SizeBytes holds the value of the "size_bytes" field.
	SizeBytes int64 `json:"size_bytes,omitempty"`
	// Sha256 holds the value of the "sha256" field.
	Sha256 *string `json:"sha256,omitempty"`
	// Status holds the value of the "status" field.
	Status fileobject.Status `json:"status,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// UploadedAt holds the value of the "uploaded_at" field.
	UploadedAt *time.Time `json:"uploaded_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FileObjectQuery when eager-loading is set.
	Edges        FileObjectEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FileObjectEdges holds the relations/edges for other nodes in the graph.
type FileObjectEdges struct {
	// OwnerUser holds the value of the owner_user edge.
	OwnerUser *User `json:"owner_user,omitempty"`
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OwnerUserOrErr returns the OwnerUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FileObjectEdges) OwnerUserOrErr() (*User, error) {
	if e.OwnerUser != nil {
		return e.OwnerUser, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner_user"}
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FileObjectEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FileObject) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case fileobject.FieldMetadata:
			values[i] = new([]byte)
		case fileobject.FieldID, fileobject.FieldOwnerUserID, fileobject.FieldAPIKeyID, fileobject.FieldSizeBytes:
			values[i] = new(sql.NullInt64)
		case fileobject.FieldPurpose, fileobject.FieldStorageProvider, fileobject.FieldBucket, fileobject.FieldObjectKey, fileobject.FieldOriginalFilename, fileobject.FieldMimeType, fileobject.FieldSha256, fileobject.FieldStatus:
			values[i] = new(sql.NullString)
		case fileobject.FieldCreatedAt, fileobject.FieldUpdatedAt, fileobject.FieldDeletedAt, fileobject.FieldUploadedAt, fileobject.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FileObject fields.
func (_m *FileObject) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case fileobject.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case fileobject.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case fileobject.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case fileobject.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case fileobject.FieldOwnerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value.Valid {
				_m.OwnerUserID = value.Int64
			}
		case fileobject.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = new(int64)
				*_m.APIKeyID = value.Int64
			}
		case fileobject.FieldPurpose:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field purpose", values[i])
			} else if value.Valid {
				_m.Purpose = value.String
			}
		case fileobject.FieldStorageProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field storage_provider", values[i])
			} else if value.Valid {
				_m.StorageProvider = value.String
			}
		case fileobject.FieldBucket:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bucket", values[i])
			} else if value.Valid {
				_m.Bucket = value.String
			}
		case fileobject.FieldObjectKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field object_key", values[i])
			} else if value.Valid {
				_m.ObjectKey = value.String
			}
		case fileobject.FieldOriginalFilename:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_filename", values[i])
			} else if value.Valid {
				_m.OriginalFilename = new(string)
				*_m.OriginalFilename = value.String
			}
		case fileobject.FieldMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime_type", values[i])
			} else if value.Valid {
				_m.MimeType = value.String
			}
		case fileobject.FieldSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size_bytes", values[i])
			} else if value.Valid {
				_m.SizeBytes = value.Int64
			}
		case fileobject.FieldSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sha256", values[i])
			} else if value.Valid {
				_m.Sha256 = new(string)
				*_m.Sha256 = value.String
			}
		case fileobject.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = fileobject.Status(value.String)
			}
		case fileobject.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case fileobject.FieldUploadedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field uploaded_at", values[i])
			} else if value.Valid {
				_m.UploadedAt = new(time.Time)
				*_m.UploadedAt = value.Time
			}
		case fileobject.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FileObject.
// This includes values selected through modifiers, order, etc.
func (_m *FileObject) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwnerUser queries the "owner_user" edge of the FileObject entity.
func (_m *FileObject) QueryOwnerUser() *UserQuery {
	return NewFileObjectClient(_m.config).QueryOwnerUser(_m)
}

// QueryAPIKey queries the "api_key" edge of the FileObject entity.
func (_m *FileObject) QueryAPIKey() *APIKeyQuery {
	return NewFileObjectClient(_m.config).QueryAPIKey(_m)
}

// Update returns a builder for updating this FileObject.
// Note that you need to call FileObject.Unwrap() before calling this method if this FileObject
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FileObject) Update() *FileObjectUpdateOne {
	return NewFileObjectClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FileObject entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FileObject) Unwrap() *FileObject {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FileObject is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FileObject) String() string {
	var builder strings.Builder
	builder.WriteString("FileObject(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("owner_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerUserID))
	builder.WriteString(", ")
	if v := _m.APIKeyID; v != nil {
		builder.WriteString("api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("purpose=")
	builder.WriteString(_m.Purpose)
	builder.WriteString(", ")
	builder.WriteString("storage_provider=")
	builder.WriteString(_m.StorageProvider)
	builder.WriteString(", ")
	builder.WriteString("bucket=")
	builder.WriteString(_m.Bucket)
	builder.WriteString(", ")
	builder.WriteString("object_key=")
	builder.WriteString(_m.ObjectKey)
	builder.WriteString(", ")
	if v := _m.OriginalFilename; v != nil {
		builder.WriteString("original_filename=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("mime_type=")
	builder.WriteString(_m.MimeType)
	builder.WriteString(", ")
	builder.WriteString("size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.SizeBytes))
	builder.WriteString(", ")
	if v := _m.Sha256; v != nil {
		builder.WriteString("sha256=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	if v := _m.UploadedAt; v != nil {
		builder.WriteString("uploaded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// FileObjects is a parsable slice of FileObject.
type FileObjects []*FileObject
