// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/fileobject"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// FileObjectUpdate is the builder for updating FileObject entities.
type FileObjectUpdate struct {
	config
	hooks    []Hook
	mutation *FileObjectMutation
}

// Where appends a list predicates to the FileObjectUpdate builder.
func (_u *FileObjectUpdate) Where(ps ...predicate.FileObject) *FileObjectUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FileObjectUpdate) SetUpdatedAt(v time.Time) *FileObjectUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FileObjectUpdate) SetDeletedAt(v time.Time) *FileObjectUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FileObjectUpdate) SetNillableDeletedAt(v *time.Time) *FileObjectUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FileObjectUpdate) ClearDeletedAt() *FileObjectUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *FileObjectUpdate) SetOwnerUserID(v int64) *FileObjectUpdate {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *FileObjectUpdate) SetNillableOwnerUserID(v *int64) *FileObjectUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *FileObjectUpdate) SetAPIKeyID(v int64) *FileObjectUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *FileObjectUpdate) SetNillableAPIKeyID(v *int64) *FileObjectUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *FileObjectUpdate) ClearAPIKeyID() *FileObjectUpdate {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetPurpose sets the "purpose" field.
func (_u *FileObjectUpdate) SetPurpose(v string) *FileObjectUpdate {
	_u.mutation.SetPurpose(v)
	return _u
}

// SetNillablePurpose sets the "purpose" field if the given value is not nil.
func (_u *FileObjectUpdate) SetNillablePurpose(v *string) *FileObjectUpdate {
	if v != nil {
		_u.SetPurpose(*v)
	}
	return _u
}

// SetStorageProvider sets the "storage_provider" field.
func (_u *FileObjectUpdate) SetStorageProvider(v string) *FileObjectUpdate {
	_u.mutation.SetStorageProvider(v)
	return _u
}

// SetNillableStorageProvider sets the "storage_provider" field if the given value is not nil.
func (_u *FileObjectUpdate) SetNillableStorageProvider(v *string) *FileObjectUpdate {
	if v != nil {
		_u.SetStorageProvider(*v)
	}
	return _u
}

// SetBucket sets the "bucket" field.
func (_u *FileObjectUpdate) SetBucket(v string) *FileObjectUpdate {
	_u.mutation.SetBucket(v)
	return _u
}

// SetNillableBucket sets the "bucket" field if the given value is not nil.
func (_u *FileObjectUpdate) SetNillableBucket(v *string) *FileObjectUpdate {
	if v != nil {
		_u.SetBucket(*v)
	}
	return _u
}

// SetObjectKey sets the "object_key" field.
func (_u *FileObjectUpdate) SetObjectKey(v string) *FileObjectUpdate {
	_u.mutation.SetObjectKey(v)
	return _u
}

// SetNillableObjectKey sets the "object_key" field if the given value is not nil.
func (_u *FileObjectUpdate) SetNillableObjectKey(v *string) *FileObjectUpdate {
	if v != nil {
		_u.SetObjectKey(*v)
	}
	return _u
}

// SetOriginalFilename sets the "original_filename" field.
func (_u *FileObjectUpdate) SetOriginalFilename(v string) *FileObjectUpdate {
	_u.mutation.SetOriginalFilename(v)
	return _u
}

// SetNillableOriginalFilename sets the "original_filename" field if the given value is not nil.
func (_u *FileObjectUpdate) SetNillableOriginalFilename(v *string) *FileObjectUpdate {
	if v != nil {
		_u.SetOriginalFilename(*v)
	}
	return _u
}

// ClearOriginalFilename clears the value of the "original_filename" field.
func (_u *FileObjectUpdate) ClearOriginalFilename() *FileObjectUpdate {
	_u.mutation.ClearOriginalFilename()
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *FileObjectUpdate) SetMimeType(v string) *FileObjectUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *FileObjectUpdate) SetNillableMimeType(v *string) *FileObjectUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *FileObjectUpdate) SetSizeBytes(v int64) *FileObjectUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *FileObjectUpdate) SetNillableSizeBytes(v *int64) *FileObjectUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *FileObjectUpdate) AddSizeBytes(v int64) *FileObjectUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *FileObjectUpdate) SetSha256(v string) *FileObjectUpdate {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *FileObjectUpdate) SetNillableSha256(v *string) *FileObjectUpdate {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// ClearSha256 clears the value of the "sha256" field.
func (_u *FileObjectUpdate) ClearSha256() *FileObjectUpdate {
	_u.mutation.ClearSha256()
	return _u
}

// SetStatus sets the "status" field.
func (_u *FileObjectUpdate) SetStatus(v fileobject.Status) *FileObjectUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FileObjectUpdate) SetNillableStatus(v *fileobject.Status) *FileObjectUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *FileObjectUpdate) SetMetadata(v map[string]interface{}) *FileObjectUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetUploadedAt sets the "uploaded_at" field.
func (_u *FileObjectUpdate) SetUploadedAt(v time.Time) *FileObjectUpdate {
	_u.mutation.SetUploadedAt(v)
	return _u
}

// SetNillableUploadedAt sets the "uploaded_at" field if the given value is not nil.
func (_u *FileObjectUpdate) SetNillableUploadedAt(v *time.Time) *FileObjectUpdate {
	if v != nil {
		_u.SetUploadedAt(*v)
	}
	return _u
}

// ClearUploadedAt clears the value of the "uploaded_at" field.
func (_u *FileObjectUpdate) ClearUploadedAt() *FileObjectUpdate {
	_u.mutation.ClearUploadedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *FileObjectUpdate) SetExpiresAt(v time.Time) *FileObjectUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *FileObjectUpdate) SetNillableExpiresAt(v *time.Time) *FileObjectUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *FileObjectUpdate) ClearExpiresAt() *FileObjectUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetOwnerUser sets the "owner_user" edge to the User entity.
func (_u *FileObjectUpdate) SetOwnerUser(v *User) *FileObjectUpdate {
	return _u.SetOwnerUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *FileObjectUpdate) SetAPIKey(v *APIKey) *FileObjectUpdate {
	return _u.SetAPIKeyID(v.ID)
}

// Mutation returns the FileObjectMutation object of the builder.
func (_u *FileObjectUpdate) Mutation() *FileObjectMutation {
	return _u.mutation
}

// ClearOwnerUser clears the "owner_user" edge to the User entity.
func (_u *FileObjectUpdate) ClearOwnerUser() *FileObjectUpdate {
	_u.mutation.ClearOwnerUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *FileObjectUpdate) ClearAPIKey() *FileObjectUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FileObjectUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FileObjectUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FileObjectUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FileObjectUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FileObjectUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if fileobject.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized fileobject.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := fileobject.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *FileObjectUpdate) check() error {
	if v, ok := _u.mutation.Purpose(); ok {
		if err := fileobject.PurposeValidator(v); err != nil {
			return &ValidationError{Name: "purpose", err: fmt.Errorf(`ent: validator failed for field "FileObject.purpose": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StorageProvider(); ok {
		if err := fileobject.StorageProviderValidator(v); err != nil {
			return &ValidationError{Name: "storage_provider", err: fmt.Errorf(`ent: validator failed for field "FileObject.storage_provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bucket(); ok {
		if err := fileobject.BucketValidator(v); err != nil {
			return &ValidationError{Name: "bucket", err: fmt.Errorf(`ent: validator failed for field "FileObject.bucket": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ObjectKey(); ok {
		if err := fileobject.ObjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "object_key", err: fmt.Errorf(`ent: validator failed for field "FileObject.object_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginalFilename(); ok {
		if err := fileobject.OriginalFilenameValidator(v); err != nil {
			return &ValidationError{Name: "original_filename", err: fmt.Errorf(`ent: validator failed for field "FileObject.original_filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := fileobject.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "FileObject.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := fileobject.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "FileObject.sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := fileobject.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FileObject.status": %w`, err)}
		}
	}
	if _u.mutation.OwnerUserCleared() && len(_u.mutation.OwnerUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FileObject.owner_user"`)
	}
	return nil
}

func (_u *FileObjectUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fileobject.Table, fileobject.Columns, sqlgraph.NewFieldSpec(fileobject.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(fileobject.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(fileobject.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(fileobject.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Purpose(); ok {
		_spec.SetField(fileobject.FieldPurpose, field.TypeString, value)
	}
	if value, ok := _u.mutation.StorageProvider(); ok {
		_spec.SetField(fileobject.FieldStorageProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bucket(); ok {
		_spec.SetField(fileobject.FieldBucket, field.TypeString, value)
	}
	if value, ok := _u.mutation.ObjectKey(); ok {
		_spec.SetField(fileobject.FieldObjectKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalFilename(); ok {
		_spec.SetField(fileobject.FieldOriginalFilename, field.TypeString, value)
	}
	if _u.mutation.OriginalFilenameCleared() {
		_spec.ClearField(fileobject.FieldOriginalFilename, field.TypeString)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(fileobject.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(fileobject.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(fileobject.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(fileobject.FieldSha256, field.TypeString, value)
	}
	if _u.mutation.Sha256Cleared() {
		_spec.ClearField(fileobject.FieldSha256, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(fileobject.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(fileobject.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UploadedAt(); ok {
		_spec.SetField(fileobject.FieldUploadedAt, field.TypeTime, value)
	}
	if _u.mutation.UploadedAtCleared() {
		_spec.ClearField(fileobject.FieldUploadedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(fileobject.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(fileobject.FieldExpiresAt, field.TypeTime)
	}
	if _u.mutation.OwnerUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fileobject.OwnerUserTable,
			Columns: []string{fileobject.OwnerUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fileobject.OwnerUserTable,
			Columns: []string{fileobject.OwnerUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fileobject.APIKeyTable,
			Columns: []string{fileobject.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fileobject.APIKeyTable,
			Columns: []string{fileobject.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fileobject.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FileObjectUpdateOne is the builder for updating a single FileObject entity.
type FileObjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FileObjectMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FileObjectUpdateOne) SetUpdatedAt(v time.Time) *FileObjectUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FileObjectUpdateOne) SetDeletedAt(v time.Time) *FileObjectUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FileObjectUpdateOne) SetNillableDeletedAt(v *time.Time) *FileObjectUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FileObjectUpdateOne) ClearDeletedAt() *FileObjectUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *FileObjectUpdateOne) SetOwnerUserID(v int64) *FileObjectUpdateOne {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *FileObjectUpdateOne) SetNillableOwnerUserID(v *int64) *FileObjectUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *FileObjectUpdateOne) SetAPIKeyID(v int64) *FileObjectUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *FileObjectUpdateOne) SetNillableAPIKeyID(v *int64) *FileObjectUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *FileObjectUpdateOne) ClearAPIKeyID() *FileObjectUpdateOne {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetPurpose sets the "purpose" field.
func (_u *FileObjectUpdateOne) SetPurpose(v string) *FileObjectUpdateOne {
	_u.mutation.SetPurpose(v)
	return _u
}

// SetNillablePurpose sets the "purpose" field if the given value is not nil.
func (_u *FileObjectUpdateOne) SetNillablePurpose(v *string) *FileObjectUpdateOne {
	if v != nil {
		_u.SetPurpose(*v)
	}
	return _u
}

// SetStorageProvider sets the "storage_provider" field.
func (_u *FileObjectUpdateOne) SetStorageProvider(v string) *FileObjectUpdateOne {
	_u.mutation.SetStorageProvider(v)
	return _u
}

// SetNillableStorageProvider sets the "storage_provider" field if the given value is not nil.
func (_u *FileObjectUpdateOne) SetNillableStorageProvider(v *string) *FileObjectUpdateOne {
	if v != nil {
		_u.SetStorageProvider(*v)
	}
	return _u
}

// SetBucket sets the "bucket" field.
func (_u *FileObjectUpdateOne) SetBucket(v string) *FileObjectUpdateOne {
	_u.mutation.SetBucket(v)
	return _u
}

// SetNillableBucket sets the "bucket" field if the given value is not nil.
func (_u *FileObjectUpdateOne) SetNillableBucket(v *string) *FileObjectUpdateOne {
	if v != nil {
		_u.SetBucket(*v)
	}
	return _u
}

// SetObjectKey sets the "object_key" field.
func (_u *FileObjectUpdateOne) SetObjectKey(v string) *FileObjectUpdateOne {
	_u.mutation.SetObjectKey(v)
	return _u
}

// SetNillableObjectKey sets the "object_key" field if the given value is not nil.
func (_u *FileObjectUpdateOne) SetNillableObjectKey(v *string) *FileObjectUpdateOne {
	if v != nil {
		_u.SetObjectKey(*v)
	}
	return _u
}

// SetOriginalFilename sets the "original_filename" field.
func (_u *FileObjectUpdateOne) SetOriginalFilename(v string) *FileObjectUpdateOne {
	_u.mutation.SetOriginalFilename(v)
	return _u
}

// SetNillableOriginalFilename sets the "original_filename" field if the given value is not nil.
func (_u *FileObjectUpdateOne) SetNillableOriginalFilename(v *string) *FileObjectUpdateOne {
	if v != nil {
		_u.SetOriginalFilename(*v)
	}
	return _u
}

// ClearOriginalFilename clears the value of the "original_filename" field.
func (_u *FileObjectUpdateOne) ClearOriginalFilename() *FileObjectUpdateOne {
	_u.mutation.ClearOriginalFilename()
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *FileObjectUpdateOne) SetMimeType(v string) *FileObjectUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *FileObjectUpdateOne) SetNillableMimeType(v *string) *FileObjectUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *FileObjectUpdateOne) SetSizeBytes(v int64) *FileObjectUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *FileObjectUpdateOne) SetNillableSizeBytes(v *int64) *FileObjectUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *FileObjectUpdateOne) AddSizeBytes(v int64) *FileObjectUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *FileObjectUpdateOne) SetSha256(v string) *FileObjectUpdateOne {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *FileObjectUpdateOne) SetNillableSha256(v *string) *FileObjectUpdateOne {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// ClearSha256 clears the value of the "sha256" field.
func (_u *FileObjectUpdateOne) ClearSha256() *FileObjectUpdateOne {
	_u.mutation.ClearSha256()
	return _u
}

// SetStatus sets the "status" field.
func (_u *FileObjectUpdateOne) SetStatus(v fileobject.Status) *FileObjectUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FileObjectUpdateOne) SetNillableStatus(v *fileobject.Status) *FileObjectUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *FileObjectUpdateOne) SetMetadata(v map[string]interface{}) *FileObjectUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetUploadedAt sets the "uploaded_at" field.
func (_u *FileObjectUpdateOne) SetUploadedAt(v time.Time) *FileObjectUpdateOne {
	_u.mutation.SetUploadedAt(v)
	return _u
}

// SetNillableUploadedAt sets the "uploaded_at" field if the given value is not nil.
func (_u *FileObjectUpdateOne) SetNillableUploadedAt(v *time.Time) *FileObjectUpdateOne {
	if v != nil {
		_u.SetUploadedAt(*v)
	}
	return _u
}

// ClearUploadedAt clears the value of the "uploaded_at" field.
func (_u *FileObjectUpdateOne) ClearUploadedAt() *FileObjectUpdateOne {
	_u.mutation.ClearUploadedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *FileObjectUpdateOne) SetExpiresAt(v time.Time) *FileObjectUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *FileObjectUpdateOne) SetNillableExpiresAt(v *time.Time) *FileObjectUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *FileObjectUpdateOne) ClearExpiresAt() *FileObjectUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetOwnerUser sets the "owner_user" edge to the User entity.
func (_u *FileObjectUpdateOne) SetOwnerUser(v *User) *FileObjectUpdateOne {
	return _u.SetOwnerUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *FileObjectUpdateOne) SetAPIKey(v *APIKey) *FileObjectUpdateOne {
	return _u.SetAPIKeyID(v.ID)
}

// Mutation returns the FileObjectMutation object of the builder.
func (_u *FileObjectUpdateOne) Mutation() *FileObjectMutation {
	return _u.mutation
}

// ClearOwnerUser clears the "owner_user" edge to the User entity.
func (_u *FileObjectUpdateOne) ClearOwnerUser() *FileObjectUpdateOne {
	_u.mutation.ClearOwnerUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *FileObjectUpdateOne) ClearAPIKey() *FileObjectUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// Where appends a list predicates to the FileObjectUpdate builder.
func (_u *FileObjectUpdateOne) Where(ps ...predicate.FileObject) *FileObjectUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FileObjectUpdateOne) Select(field string, fields ...string) *FileObjectUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FileObject entity.
func (_u *FileObjectUpdateOne) Save(ctx context.Context) (*FileObject, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FileObjectUpdateOne) SaveX(ctx context.Context) *FileObject {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FileObjectUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FileObjectUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FileObjectUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if fileobject.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized fileobject.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := fileobject.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *FileObjectUpdateOne) check() error {
	if v, ok := _u.mutation.Purpose(); ok {
		if err := fileobject.PurposeValidator(v); err != nil {
			return &ValidationError{Name: "purpose", err: fmt.Errorf(`ent: validator failed for field "FileObject.purpose": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StorageProvider(); ok {
		if err := fileobject.StorageProviderValidator(v); err != nil {
			return &ValidationError{Name: "storage_provider", err: fmt.Errorf(`ent: validator failed for field "FileObject.storage_provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bucket(); ok {
		if err := fileobject.BucketValidator(v); err != nil {
			return &ValidationError{Name: "bucket", err: fmt.Errorf(`ent: validator failed for field "FileObject.bucket": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ObjectKey(); ok {
		if err := fileobject.ObjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "object_key", err: fmt.Errorf(`ent: validator failed for field "FileObject.object_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginalFilename(); ok {
		if err := fileobject.OriginalFilenameValidator(v); err != nil {
			return &ValidationError{Name: "original_filename", err: fmt.Errorf(`ent: validator failed for field "FileObject.original_filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := fileobject.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "FileObject.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := fileobject.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "FileObject.sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := fileobject.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FileObject.status": %w`, err)}
		}
	}
	if _u.mutation.OwnerUserCleared() && len(_u.mutation.OwnerUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FileObject.owner_user"`)
	}
	return nil
}

func (_u *FileObjectUpdateOne) sqlSave(ctx context.Context) (_node *FileObject, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fileobject.Table, fileobject.Columns, sqlgraph.NewFieldSpec(fileobject.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FileObject.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fileobject.FieldID)
		for _, f := range fields {
			if !fileobject.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != fileobject.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(fileobject.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(fileobject.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(fileobject.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Purpose(); ok {
		_spec.SetField(fileobject.FieldPurpose, field.TypeString, value)
	}
	if value, ok := _u.mutation.StorageProvider(); ok {
		_spec.SetField(fileobject.FieldStorageProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bucket(); ok {
		_spec.SetField(fileobject.FieldBucket, field.TypeString, value)
	}
	if value, ok := _u.mutation.ObjectKey(); ok {
		_spec.SetField(fileobject.FieldObjectKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalFilename(); ok {
		_spec.SetField(fileobject.FieldOriginalFilename, field.TypeString, value)
	}
	if _u.mutation.OriginalFilenameCleared() {
		_spec.ClearField(fileobject.FieldOriginalFilename, field.TypeString)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(fileobject.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(fileobject.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(fileobject.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(fileobject.FieldSha256, field.TypeString, value)
	}
	if _u.mutation.Sha256Cleared() {
		_spec.ClearField(fileobject.FieldSha256, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(fileobject.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(fileobject.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UploadedAt(); ok {
		_spec.SetField(fileobject.FieldUploadedAt, field.TypeTime, value)
	}
	if _u.mutation.UploadedAtCleared() {
		_spec.ClearField(fileobject.FieldUploadedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(fileobject.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(fileobject.FieldExpiresAt, field.TypeTime)
	}
	if _u.mutation.OwnerUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fileobject.OwnerUserTable,
			Columns: []string{fileobject.OwnerUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fileobject.OwnerUserTable,
			Columns: []string{fileobject.OwnerUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fileobject.APIKeyTable,
			Columns: []string{fileobject.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fileobject.APIKeyTable,
			Columns: []string{fileobject.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FileObject{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fileobject.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
