// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/fileobject"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// FileObjectCreate is the builder for creating a FileObject entity.
type FileObjectCreate struct {
	config
	mutation *FileObjectMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *FileObjectCreate) SetCreatedAt(v time.Time) *FileObjectCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FileObjectCreate) SetNillableCreatedAt(v *time.Time) *FileObjectCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FileObjectCreate) SetUpdatedAt(v time.Time) *FileObjectCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FileObjectCreate) SetNillableUpdatedAt(v *time.Time) *FileObjectCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *FileObjectCreate) SetDeletedAt(v time.Time) *FileObjectCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *FileObjectCreate) SetNillableDeletedAt(v *time.Time) *FileObjectCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *FileObjectCreate) SetOwnerUserID(v int64) *FileObjectCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *FileObjectCreate) SetAPIKeyID(v int64) *FileObjectCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *FileObjectCreate) SetNillableAPIKeyID(v *int64) *FileObjectCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetPurpose sets the "purpose" field.
func (_c *FileObjectCreate) SetPurpose(v string) *FileObjectCreate {
	_c.mutation.SetPurpose(v)
	return _c
}

// SetNillablePurpose sets the "purpose" field if the given value is not nil.
func (_c *FileObjectCreate) SetNillablePurpose(v *string) *FileObjectCreate {
	if v != nil {
		_c.SetPurpose(*v)
	}
	return _c
}

// SetStorageProvider sets the "storage_provider" field.
func (_c *FileObjectCreate) SetStorageProvider(v string) *FileObjectCreate {
	_c.mutation.SetStorageProvider(v)
	return _c
}

// SetNillableStorageProvider sets the "storage_provider" field if the given value is not nil.
func (_c *FileObjectCreate) SetNillableStorageProvider(v *string) *FileObjectCreate {
	if v != nil {
		_c.SetStorageProvider(*v)
	}
	return _c
}

// SetBucket sets the "bucket" field.
func (_c *FileObjectCreate) SetBucket(v string) *FileObjectCreate {
	_c.mutation.SetBucket(v)
	return _c
}

// SetObjectKey sets the "object_key" field.
func (_c *FileObjectCreate) SetObjectKey(v string) *FileObjectCreate {
	_c.mutation.SetObjectKey(v)
	return _c
}

// SetOriginalFilename sets the "original_filename" field.
func (_c *FileObjectCreate) SetOriginalFilename(v string) *FileObjectCreate {
	_c.mutation.SetOriginalFilename(v)
	return _c
}

// SetNillableOriginalFilename sets the "original_filename" field if the given value is not nil.
func (_c *FileObjectCreate) SetNillableOriginalFilename(v *string) *FileObjectCreate {
	if v != nil {
		_c.SetOriginalFilename(*v)
	}
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *FileObjectCreate) SetMimeType(v string) *FileObjectCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *FileObjectCreate) SetSizeBytes(v int64) *FileObjectCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_c *FileObjectCreate) SetNillableSizeBytes(v *int64) *FileObjectCreate {
	if v != nil {
		_c.SetSizeBytes(*v)
	}
	return _c
}

// SetSha256 sets the "sha256" field.
func (_c *FileObjectCreate) SetSha256(v string) *FileObjectCreate {
	_c.mutation.SetSha256(v)
	return _c
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_c *FileObjectCreate) SetNillableSha256(v *string) *FileObjectCreate {
	if v != nil {
		_c.SetSha256(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *FileObjectCreate) SetStatus(v fileobject.Status) *FileObjectCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *FileObjectCreate) SetNillableStatus(v *fileobject.Status) *FileObjectCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *FileObjectCreate) SetMetadata(v map[string]interface{}) *FileObjectCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetUploadedAt sets the "uploaded_at" field.
func (_c *FileObjectCreate) SetUploadedAt(v time.Time) *FileObjectCreate {
	_c.mutation.SetUploadedAt(v)
	return _c
}

// SetNillableUploadedAt sets the "uploaded_at" field if the given value is not nil.
func (_c *FileObjectCreate) SetNillableUploadedAt(v *time.Time) *FileObjectCreate {
	if v != nil {
		_c.SetUploadedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *FileObjectCreate) SetExpiresAt(v time.Time) *FileObjectCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *FileObjectCreate) SetNillableExpiresAt(v *time.Time) *FileObjectCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetOwnerUser sets the "owner_user" edge to the User entity.
func (_c *FileObjectCreate) SetOwnerUser(v *User) *FileObjectCreate {
	return _c.SetOwnerUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *FileObjectCreate) SetAPIKey(v *APIKey) *FileObjectCreate {
	return _c.SetAPIKeyID(v.ID)
}

// Mutation returns the FileObjectMutation object of the builder.
func (_c *FileObjectCreate) Mutation() *FileObjectMutation {
	return _c.mutation
}

// Save creates the FileObject in the database.
func (_c *FileObjectCreate) Save(ctx context.Context) (*FileObject, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FileObjectCreate) SaveX(ctx context.Context) *FileObject {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileObjectCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileObjectCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FileObjectCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if fileobject.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized fileobject.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := fileobject.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if fileobject.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized fileobject.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := fileobject.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Purpose(); !ok {
		v := fileobject.DefaultPurpose
		_c.mutation.SetPurpose(v)
	}
	if _, ok := _c.mutation.StorageProvider(); !ok {
		v := fileobject.DefaultStorageProvider
		_c.mutation.SetStorageProvider(v)
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		v := fileobject.DefaultSizeBytes
		_c.mutation.SetSizeBytes(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := fileobject.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		if fileobject.DefaultMetadata == nil {
			return fmt.Errorf("ent: uninitialized fileobject.DefaultMetadata (forgotten import ent/runtime?)")
		}
		v := fileobject.DefaultMetadata()
		_c.mutation.SetMetadata(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *FileObjectCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FileObject.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "FileObject.updated_at"`)}
	}
	if _, ok := _c.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "FileObject.owner_user_id"`)}
	}
	if _, ok := _c.mutation.Purpose(); !ok {
		return &ValidationError{Name: "purpose", err: errors.New(`ent: missing required field "FileObject.purpose"`)}
	}
	if v, ok := _c.mutation.Purpose(); ok {
		if err := fileobject.PurposeValidator(v); err != nil {
			return &ValidationError{Name: "purpose", err: fmt.Errorf(`ent: validator failed for field "FileObject.purpose": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StorageProvider(); !ok {
		return &ValidationError{Name: "storage_provider", err: errors.New(`ent: missing required field "FileObject.storage_provider"`)}
	}
	if v, ok := _c.mutation.StorageProvider(); ok {
		if err := fileobject.StorageProviderValidator(v); err != nil {
			return &ValidationError{Name: "storage_provider", err: fmt.Errorf(`ent: validator failed for field "FileObject.storage_provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Bucket(); !ok {
		return &ValidationError{Name: "bucket", err: errors.New(`ent: missing required field "FileObject.bucket"`)}
	}
	if v, ok := _c.mutation.Bucket(); ok {
		if err := fileobject.BucketValidator(v); err != nil {
			return &ValidationError{Name: "bucket", err: fmt.Errorf(`ent: validator failed for field "FileObject.bucket": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ObjectKey(); !ok {
		return &ValidationError{Name: "object_key", err: errors.New(`ent: missing required field "FileObject.object_key"`)}
	}
	if v, ok := _c.mutation.ObjectKey(); ok {
		if err := fileobject.ObjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "object_key", err: fmt.Errorf(`ent: validator failed for field "FileObject.object_key": %w`, err)}
		}
	}
	if v, ok := _c.mutation.OriginalFilename(); ok {
		if err := fileobject.OriginalFilenameValidator(v); err != nil {
			return &ValidationError{Name: "original_filename", err: fmt.Errorf(`ent: validator failed for field "FileObject.original_filename": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		return &ValidationError{Name: "mime_type", err: errors.New(`ent: missing required field "FileObject.mime_type"`)}
	}
	if v, ok := _c.mutation.MimeType(); ok {
		if err := fileobject.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "FileObject.mime_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "FileObject.size_bytes"`)}
	}
	if v, ok := _c.mutation.Sha256(); ok {
		if err := fileobject.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "FileObject.sha256": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "FileObject.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := fileobject.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FileObject.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "FileObject.metadata"`)}
	}
	if len(_c.mutation.OwnerUserIDs()) == 0 {
		return &ValidationError{Name: "owner_user", err: errors.New(`ent: missing required edge "FileObject.owner_user"`)}
	}
	return nil
}

func (_c *FileObjectCreate) sqlSave(ctx context.Context) (*FileObject, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FileObjectCreate) createSpec() (*FileObject, *sqlgraph.CreateSpec) {
	var (
		_node = &FileObject{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(fileobject.Table, sqlgraph.NewFieldSpec(fileobject.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(fileobject.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(fileobject.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(fileobject.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Purpose(); ok {
		_spec.SetField(fileobject.FieldPurpose, field.TypeString, value)
		_node.Purpose = value
	}
	if value, ok := _c.mutation.StorageProvider(); ok {
		_spec.SetField(fileobject.FieldStorageProvider, field.TypeString, value)
		_node.StorageProvider = value
	}
	if value, ok := _c.mutation.Bucket(); ok {
		_spec.SetField(fileobject.FieldBucket, field.TypeString, value)
		_node.Bucket = value
	}
	if value, ok := _c.mutation.ObjectKey(); ok {
		_spec.SetField(fileobject.FieldObjectKey, field.TypeString, value)
		_node.ObjectKey = value
	}
	if value, ok := _c.mutation.OriginalFilename(); ok {
		_spec.SetField(fileobject.FieldOriginalFilename, field.TypeString, value)
		_node.OriginalFilename = &value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(fileobject.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(fileobject.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.Sha256(); ok {
		_spec.SetField(fileobject.FieldSha256, field.TypeString, value)
		_node.Sha256 = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(fileobject.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(fileobject.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.UploadedAt(); ok {
		_spec.SetField(fileobject.FieldUploadedAt, field.TypeTime, value)
		_node.UploadedAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(fileobject.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if nodes := _c.mutation.OwnerUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fileobject.OwnerUserTable,
			Columns: []string{fileobject.OwnerUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OwnerUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fileobject.APIKeyTable,
			Columns: []string{fileobject.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FileObject.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FileObjectUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *FileObjectCreate) OnConflict(opts ...sql.ConflictOption) *FileObjectUpsertOne {
	_c.conflict = opts
	return &FileObjectUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FileObject.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FileObjectCreate) OnConflictColumns(columns ...string) *FileObjectUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FileObjectUpsertOne{
		create: _c,
	}
}

type (
	// FileObjectUpsertOne is the builder for "upsert"-ing
	//  one FileObject node.
	FileObjectUpsertOne struct {
		create *FileObjectCreate
	}

	// FileObjectUpsert is the "OnConflict" setter.
	FileObjectUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *FileObjectUpsert) SetUpdatedAt(v time.Time) *FileObjectUpsert {
	u.Set(fileobject.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FileObjectUpsert) UpdateUpdatedAt() *FileObjectUpsert {
	u.SetExcluded(fileobject.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *FileObjectUpsert) SetDeletedAt(v time.Time) *FileObjectUpsert {
	u.Set(fileobject.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *FileObjectUpsert) UpdateDeletedAt() *FileObjectUpsert {
	u.SetExcluded(fileobject.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *FileObjectUpsert) ClearDeletedAt() *FileObjectUpsert {
	u.SetNull(fileobject.FieldDeletedAt)
	return u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *FileObjectUpsert) SetOwnerUserID(v int64) *FileObjectUpsert {
	u.Set(fileobject.FieldOwnerUserID, v)
	return u
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *FileObjectUpsert) UpdateOwnerUserID() *FileObjectUpsert {
	u.SetExcluded(fileobject.FieldOwnerUserID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *FileObjectUpsert) SetAPIKeyID(v int64) *FileObjectUpsert {
	u.Set(fileobject.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *FileObjectUpsert) UpdateAPIKeyID() *FileObjectUpsert {
	u.SetExcluded(fileobject.FieldAPIKeyID)
	return u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *FileObjectUpsert) ClearAPIKeyID() *FileObjectUpsert {
	u.SetNull(fileobject.FieldAPIKeyID)
	return u
}

// SetPurpose sets the "purpose" field.
func (u *FileObjectUpsert) SetPurpose(v string) *FileObjectUpsert {
	u.Set(fileobject.FieldPurpose, v)
	return u
}

// UpdatePurpose sets the "purpose" field to the value that was provided on create.
func (u *FileObjectUpsert) UpdatePurpose() *FileObjectUpsert {
	u.SetExcluded(fileobject.FieldPurpose)
	return u
}

// SetStorageProvider sets the "storage_provider" field.
func (u *FileObjectUpsert) SetStorageProvider(v string) *FileObjectUpsert {
	u.Set(fileobject.FieldStorageProvider, v)
	return u
}

// UpdateStorageProvider sets the "storage_provider" field to the value that was provided on create.
func (u *FileObjectUpsert) UpdateStorageProvider() *FileObjectUpsert {
	u.SetExcluded(fileobject.FieldStorageProvider)
	return u
}

// SetBucket sets the "bucket" field.
func (u *FileObjectUpsert) SetBucket(v string) *FileObjectUpsert {
	u.Set(fileobject.FieldBucket, v)
	return u
}

// UpdateBucket sets the "bucket" field to the value that was provided on create.
func (u *FileObjectUpsert) UpdateBucket() *FileObjectUpsert {
	u.SetExcluded(fileobject.FieldBucket)
	return u
}

// SetObjectKey sets the "object_key" field.
func (u *FileObjectUpsert) SetObjectKey(v string) *FileObjectUpsert {
	u.Set(fileobject.FieldObjectKey, v)
	return u
}

// UpdateObjectKey sets the "object_key" field to the value that was provided on create.
func (u *FileObjectUpsert) UpdateObjectKey() *FileObjectUpsert {
	u.SetExcluded(fileobject.FieldObjectKey)
	return u
}

// SetOriginalFilename sets the "original_filename" field.
func (u *FileObjectUpsert) SetOriginalFilename(v string) *FileObjectUpsert {
	u.Set(fileobject.FieldOriginalFilename, v)
	return u
}

// UpdateOriginalFilename sets the "original_filename" field to the value that was provided on create.
func (u *FileObjectUpsert) UpdateOriginalFilename() *FileObjectUpsert {
	u.SetExcluded(fileobject.FieldOriginalFilename)
	return u
}

// ClearOriginalFilename clears the value of the "original_filename" field.
func (u *FileObjectUpsert) ClearOriginalFilename() *FileObjectUpsert {
	u.SetNull(fileobject.FieldOriginalFilename)
	return u
}

// SetMimeType sets the "mime_type" field.
func (u *FileObjectUpsert) SetMimeType(v string) *FileObjectUpsert {
	u.Set(fileobject.FieldMimeType, v)
	return u
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *FileObjectUpsert) UpdateMimeType() *FileObjectUpsert {
	u.SetExcluded(fileobject.FieldMimeType)
	return u
}

// SetSizeBytes sets the "size_bytes" field.
func (u *FileObjectUpsert) SetSizeBytes(v int64) *FileObjectUpsert {
	u.Set(fileobject.FieldSizeBytes, v)
	return u
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *FileObjectUpsert) UpdateSizeBytes() *FileObjectUpsert {
	u.SetExcluded(fileobject.FieldSizeBytes)
	return u
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *FileObjectUpsert) AddSizeBytes(v int64) *FileObjectUpsert {
	u.Add(fileobject.FieldSizeBytes, v)
	return u
}

// SetSha256 sets the "sha256" field.
func (u *FileObjectUpsert) SetSha256(v string) *FileObjectUpsert {
	u.Set(fileobject.FieldSha256, v)
	return u
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *FileObjectUpsert) UpdateSha256() *FileObjectUpsert {
	u.SetExcluded(fileobject.FieldSha256)
	return u
}

// ClearSha256 clears the value of the "sha256" field.
func (u *FileObjectUpsert) ClearSha256() *FileObjectUpsert {
	u.SetNull(fileobject.FieldSha256)
	return u
}

// SetStatus sets the "status" field.
func (u *FileObjectUpsert) SetStatus(v fileobject.Status) *FileObjectUpsert {
	u.Set(fileobject.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *FileObjectUpsert) UpdateStatus() *FileObjectUpsert {
	u.SetExcluded(fileobject.FieldStatus)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *FileObjectUpsert) SetMetadata(v map[string]interface{}) *FileObjectUpsert {
	u.Set(fileobject.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *FileObjectUpsert) UpdateMetadata() *FileObjectUpsert {
	u.SetExcluded(fileobject.FieldMetadata)
	return u
}

// SetUploadedAt sets the "uploaded_at" field.
func (u *FileObjectUpsert) SetUploadedAt(v time.Time) *FileObjectUpsert {
	u.Set(fileobject.FieldUploadedAt, v)
	return u
}

// UpdateUploadedAt sets the "uploaded_at" field to the value that was provided on create.
func (u *FileObjectUpsert) UpdateUploadedAt() *FileObjectUpsert {
	u.SetExcluded(fileobject.FieldUploadedAt)
	return u
}

// ClearUploadedAt clears the value of the "uploaded_at" field.
func (u *FileObjectUpsert) ClearUploadedAt() *FileObjectUpsert {
	u.SetNull(fileobject.FieldUploadedAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *FileObjectUpsert) SetExpiresAt(v time.Time) *FileObjectUpsert {
	u.Set(fileobject.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *FileObjectUpsert) UpdateExpiresAt() *FileObjectUpsert {
	u.SetExcluded(fileobject.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *FileObjectUpsert) ClearExpiresAt() *FileObjectUpsert {
	u.SetNull(fileobject.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.FileObject.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FileObjectUpsertOne) UpdateNewValues() *FileObjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(fileobject.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FileObject.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FileObjectUpsertOne) Ignore() *FileObjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FileObjectUpsertOne) DoNothing() *FileObjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FileObjectCreate.OnConflict
// documentation for more info.
func (u *FileObjectUpsertOne) Update(set func(*FileObjectUpsert)) *FileObjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FileObjectUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FileObjectUpsertOne) SetUpdatedAt(v time.Time) *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FileObjectUpsertOne) UpdateUpdatedAt() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *FileObjectUpsertOne) SetDeletedAt(v time.Time) *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *FileObjectUpsertOne) UpdateDeletedAt() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *FileObjectUpsertOne) ClearDeletedAt() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.ClearDeletedAt()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *FileObjectUpsertOne) SetOwnerUserID(v int64) *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *FileObjectUpsertOne) UpdateOwnerUserID() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *FileObjectUpsertOne) SetAPIKeyID(v int64) *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *FileObjectUpsertOne) UpdateAPIKeyID() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *FileObjectUpsertOne) ClearAPIKeyID() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetPurpose sets the "purpose" field.
func (u *FileObjectUpsertOne) SetPurpose(v string) *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetPurpose(v)
	})
}

// UpdatePurpose sets the "purpose" field to the value that was provided on create.
func (u *FileObjectUpsertOne) UpdatePurpose() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdatePurpose()
	})
}

// SetStorageProvider sets the "storage_provider" field.
func (u *FileObjectUpsertOne) SetStorageProvider(v string) *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetStorageProvider(v)
	})
}

// UpdateStorageProvider sets the "storage_provider" field to the value that was provided on create.
func (u *FileObjectUpsertOne) UpdateStorageProvider() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateStorageProvider()
	})
}

// SetBucket sets the "bucket" field.
func (u *FileObjectUpsertOne) SetBucket(v string) *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetBucket(v)
	})
}

// UpdateBucket sets the "bucket" field to the value that was provided on create.
func (u *FileObjectUpsertOne) UpdateBucket() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateBucket()
	})
}

// SetObjectKey sets the "object_key" field.
func (u *FileObjectUpsertOne) SetObjectKey(v string) *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetObjectKey(v)
	})
}

// UpdateObjectKey sets the "object_key" field to the value that was provided on create.
func (u *FileObjectUpsertOne) UpdateObjectKey() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateObjectKey()
	})
}

// SetOriginalFilename sets the "original_filename" field.
func (u *FileObjectUpsertOne) SetOriginalFilename(v string) *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetOriginalFilename(v)
	})
}

// UpdateOriginalFilename sets the "original_filename" field to the value that was provided on create.
func (u *FileObjectUpsertOne) UpdateOriginalFilename() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateOriginalFilename()
	})
}

// ClearOriginalFilename clears the value of the "original_filename" field.
func (u *FileObjectUpsertOne) ClearOriginalFilename() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.ClearOriginalFilename()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *FileObjectUpsertOne) SetMimeType(v string) *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *FileObjectUpsertOne) UpdateMimeType() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateMimeType()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *FileObjectUpsertOne) SetSizeBytes(v int64) *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *FileObjectUpsertOne) AddSizeBytes(v int64) *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *FileObjectUpsertOne) UpdateSizeBytes() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateSizeBytes()
	})
}

// SetSha256 sets the "sha256" field.
func (u *FileObjectUpsertOne) SetSha256(v string) *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *FileObjectUpsertOne) UpdateSha256() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateSha256()
	})
}

// ClearSha256 clears the value of the "sha256" field.
func (u *FileObjectUpsertOne) ClearSha256() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.ClearSha256()
	})
}

// SetStatus sets the "status" field.
func (u *FileObjectUpsertOne) SetStatus(v fileobject.Status) *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *FileObjectUpsertOne) UpdateStatus() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateStatus()
	})
}

// SetMetadata sets the "metadata" field.
func (u *FileObjectUpsertOne) SetMetadata(v map[string]interface{}) *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *FileObjectUpsertOne) UpdateMetadata() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateMetadata()
	})
}

// SetUploadedAt sets the "uploaded_at" field.
func (u *FileObjectUpsertOne) SetUploadedAt(v time.Time) *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetUploadedAt(v)
	})
}

// UpdateUploadedAt sets the "uploaded_at" field to the value that was provided on create.
func (u *FileObjectUpsertOne) UpdateUploadedAt() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateUploadedAt()
	})
}

// ClearUploadedAt clears the value of the "uploaded_at" field.
func (u *FileObjectUpsertOne) ClearUploadedAt() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.ClearUploadedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *FileObjectUpsertOne) SetExpiresAt(v time.Time) *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *FileObjectUpsertOne) UpdateExpiresAt() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *FileObjectUpsertOne) ClearExpiresAt() *FileObjectUpsertOne {
	return u.Update(func(s *FileObjectUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *FileObjectUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FileObjectCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FileObjectUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FileObjectUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FileObjectUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FileObjectCreateBulk is the builder for creating many FileObject entities in bulk.
type FileObjectCreateBulk struct {
	config
	err      error
	builders []*FileObjectCreate
	conflict []sql.ConflictOption
}

// Save creates the FileObject entities in the database.
func (_c *FileObjectCreateBulk) Save(ctx context.Context) ([]*FileObject, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FileObject, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FileObjectMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FileObjectCreateBulk) SaveX(ctx context.Context) []*FileObject {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileObjectCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileObjectCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FileObject.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FileObjectUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *FileObjectCreateBulk) OnConflict(opts ...sql.ConflictOption) *FileObjectUpsertBulk {
	_c.conflict = opts
	return &FileObjectUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FileObject.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FileObjectCreateBulk) OnConflictColumns(columns ...string) *FileObjectUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FileObjectUpsertBulk{
		create: _c,
	}
}

// FileObjectUpsertBulk is the builder for "upsert"-ing
// a bulk of FileObject nodes.
type FileObjectUpsertBulk struct {
	create *FileObjectCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FileObject.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FileObjectUpsertBulk) UpdateNewValues() *FileObjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(fileobject.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FileObject.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FileObjectUpsertBulk) Ignore() *FileObjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FileObjectUpsertBulk) DoNothing() *FileObjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FileObjectCreateBulk.OnConflict
// documentation for more info.
func (u *FileObjectUpsertBulk) Update(set func(*FileObjectUpsert)) *FileObjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FileObjectUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FileObjectUpsertBulk) SetUpdatedAt(v time.Time) *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FileObjectUpsertBulk) UpdateUpdatedAt() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *FileObjectUpsertBulk) SetDeletedAt(v time.Time) *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *FileObjectUpsertBulk) UpdateDeletedAt() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *FileObjectUpsertBulk) ClearDeletedAt() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.ClearDeletedAt()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *FileObjectUpsertBulk) SetOwnerUserID(v int64) *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *FileObjectUpsertBulk) UpdateOwnerUserID() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *FileObjectUpsertBulk) SetAPIKeyID(v int64) *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *FileObjectUpsertBulk) UpdateAPIKeyID() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *FileObjectUpsertBulk) ClearAPIKeyID() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetPurpose sets the "purpose" field.
func (u *FileObjectUpsertBulk) SetPurpose(v string) *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetPurpose(v)
	})
}

// UpdatePurpose sets the "purpose" field to the value that was provided on create.
func (u *FileObjectUpsertBulk) UpdatePurpose() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdatePurpose()
	})
}

// SetStorageProvider sets the "storage_provider" field.
func (u *FileObjectUpsertBulk) SetStorageProvider(v string) *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetStorageProvider(v)
	})
}

// UpdateStorageProvider sets the "storage_provider" field to the value that was provided on create.
func (u *FileObjectUpsertBulk) UpdateStorageProvider() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateStorageProvider()
	})
}

// SetBucket sets the "bucket" field.
func (u *FileObjectUpsertBulk) SetBucket(v string) *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetBucket(v)
	})
}

// UpdateBucket sets the "bucket" field to the value that was provided on create.
func (u *FileObjectUpsertBulk) UpdateBucket() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateBucket()
	})
}

// SetObjectKey sets the "object_key" field.
func (u *FileObjectUpsertBulk) SetObjectKey(v string) *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetObjectKey(v)
	})
}

// UpdateObjectKey sets the "object_key" field to the value that was provided on create.
func (u *FileObjectUpsertBulk) UpdateObjectKey() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateObjectKey()
	})
}

// SetOriginalFilename sets the "original_filename" field.
func (u *FileObjectUpsertBulk) SetOriginalFilename(v string) *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetOriginalFilename(v)
	})
}

// UpdateOriginalFilename sets the "original_filename" field to the value that was provided on create.
func (u *FileObjectUpsertBulk) UpdateOriginalFilename() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateOriginalFilename()
	})
}

// ClearOriginalFilename clears the value of the "original_filename" field.
func (u *FileObjectUpsertBulk) ClearOriginalFilename() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.ClearOriginalFilename()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *FileObjectUpsertBulk) SetMimeType(v string) *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *FileObjectUpsertBulk) UpdateMimeType() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateMimeType()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *FileObjectUpsertBulk) SetSizeBytes(v int64) *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *FileObjectUpsertBulk) AddSizeBytes(v int64) *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *FileObjectUpsertBulk) UpdateSizeBytes() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateSizeBytes()
	})
}

// SetSha256 sets the "sha256" field.
func (u *FileObjectUpsertBulk) SetSha256(v string) *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *FileObjectUpsertBulk) UpdateSha256() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateSha256()
	})
}

// ClearSha256 clears the value of the "sha256" field.
func (u *FileObjectUpsertBulk) ClearSha256() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.ClearSha256()
	})
}

// SetStatus sets the "status" field.
func (u *FileObjectUpsertBulk) SetStatus(v fileobject.Status) *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *FileObjectUpsertBulk) UpdateStatus() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateStatus()
	})
}

// SetMetadata sets the "metadata" field.
func (u *FileObjectUpsertBulk) SetMetadata(v map[string]interface{}) *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *FileObjectUpsertBulk) UpdateMetadata() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateMetadata()
	})
}

// SetUploadedAt sets the "uploaded_at" field.
func (u *FileObjectUpsertBulk) SetUploadedAt(v time.Time) *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetUploadedAt(v)
	})
}

// UpdateUploadedAt sets the "uploaded_at" field to the value that was provided on create.
func (u *FileObjectUpsertBulk) UpdateUploadedAt() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateUploadedAt()
	})
}

// ClearUploadedAt clears the value of the "uploaded_at" field.
func (u *FileObjectUpsertBulk) ClearUploadedAt() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.ClearUploadedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *FileObjectUpsertBulk) SetExpiresAt(v time.Time) *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *FileObjectUpsertBulk) UpdateExpiresAt() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *FileObjectUpsertBulk) ClearExpiresAt() *FileObjectUpsertBulk {
	return u.Update(func(s *FileObjectUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *FileObjectUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FileObjectCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FileObjectCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FileObjectUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
